export default {
  UPDATE_APPS_STATUS_OVERALL: 'UPDATE_APPS_STATUS_OVERALL',
  UPDATE_APPS_STATUS_DETAIL: 'UPDATE_APPS_STATUS_DETAIL',
  SET_APP_DETAILS_INDEX: 'SET_APP_DETAILS_INDEX',
  RESET_APP_DETAILS_INDEX: 'RESET_APP_DETAILS_INDEX',
  ADD_APP_DETAILS_HISTORY: 'ADD_APP_DETAILS_HISTORY'
};
