export default {
  UPDATE_APPS_STATUS_OVERALL: 'UPDATE_APPS_STATUS_OVERALL',
  UPDATE_APPS_STATUS_DETAIL: 'UPDATE_APPS_STATUS_DETAIL',
  UPDATE_FULL_HISTORY: 'UPDATE_FULL_HISTORY',
  SET_APP_DETAILS_INDEX: 'SET_APP_DETAILS_INDEX',
  SET_SOCKET: 'SET_SOCKET'
};
