export default {
  UPDATE_APPS_STATUS_OVERALL: 'UPDATE_APPS_STATUS_OVERALL',
  UPDATE_FULL_HISTORY: 'UPDATE_FULL_HISTORY',
  UPDATE_HISTORY: 'UPDATE_HISTORY',
  SET_APP_DETAILS_INDEX: 'SET_APP_DETAILS_INDEX',
  SET_DETAILS_REQUEST_FLAG: 'SET_DETAILS_REQUEST_FLAG',
  SET_REQUEST_USER_REDIRECT_HOME: 'SET_REQUEST_USER_REDIRECT_HOME'
};
